#!/usr/bin/env node
/*
 * Zero-dependency bundler.
 *
 * The source is written as real ES modules so core/ and api/ can be unit
 * tested under node and later lifted into a web app unchanged. Tampermonkey
 * wants one file, so this walks the import graph from src/main.js, orders the
 * modules by dependency, strips the import/export syntax and concatenates
 * everything into a single IIFE behind a userscript header.
 *
 * Because concatenation flattens every module into one scope, the build
 * FAILS on a duplicate top-level name or an import of something that is not
 * exported. Those would otherwise be silent, confusing runtime bugs.
 *
 *     node build.mjs
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import vm from 'node:vm';
import { createHash } from 'node:crypto';
import { dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const ENTRY = resolve(ROOT, 'src/main.js');
const OUT = resolve(ROOT, 'dist/torn-pumping-iron.user.js');

/*
 * Second copy at the repo root. Tampermonkey installs and auto-updates from a
 * raw URL, so the released script needs a stable path that does not move.
 */
const RELEASE_OUT = resolve(ROOT, 'torn-pumping-iron.user.js');

const REPO_RAW =
    'https://raw.githubusercontent.com/abrahamdelosreyes17-oss/' +
    'torn-pumping-iron/main/torn-pumping-iron.user.js';

const VERSION = JSON.parse(
    await readFile(resolve(ROOT, 'package.json'), 'utf8'),
).version;

/*
 * @name and @namespace are FIXED FOREVER: Tampermonkey identifies a script by
 * them, and changing either installs a second copy beside the first.
 */
const HEADER = `// ==UserScript==
// @name         Torn Pumping Iron
// @namespace    torn-pumping-iron
// @version      ${VERSION}
// @description  Gym planner and fight scout for Torn: what to take, what to train, what to buy, who you can beat. Reads the API and the page you're on; never acts for you.
// @author       abrahamdelosreyes17-oss
// @match        https://www.torn.com/*
// @match        https://abrahamdelosreyes17-oss.github.io/torn-pumping-iron/app.html*
// @match        https://abrahamdelosreyes17-oss.github.io/torn-moneymaker-releases/traders.html*
// @run-at       document-idle
// @noframes
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_registerMenuCommand
// @grant        GM_openInTab
// @grant        GM_xmlhttpRequest
// @grant        GM_addValueChangeListener
// @grant        unsafeWindow
// @connect      api.torn.com
// @connect      weav3r.dev
// @connect      ffscouter.com
// @connect      www.tornstats.com
// @connect      workers.dev
// @downloadURL  ${REPO_RAW}
// @updateURL    ${REPO_RAW}
// ==/UserScript==

/*
 * Built from src/ by build.mjs - do not edit this file directly.
 *
 * Rules this script keeps, deliberately (see README.md):
 *   - Data comes from the Torn API or from the page you are viewing. It never
 *     requests a Torn page, and never uses a hidden tab or iframe.
 *   - It never acts for you: no train, buy, use or attack, and no clicks on
 *     Torn's buttons. "Fill" types one number into Torn's box on your click;
 *     you press TRAIN yourself.
 *   - No alerts, sounds or title changes from a Torn tab. Discord pings come
 *     only from your own Worker, which reads the API.
 *   - One Torn budget (70 a minute) shared by every tab, used only by a
 *     visible tab; each third party has its own client and budget.
 *   - Each key goes only to the service that issued it: the Torn key to
 *     api.torn.com, the FFScouter key to ffscouter.com, the TornStats key to
 *     tornstats.com. TornW3B gets item ids only.
 *   - The attack-page reader only copies Torn's response; it never changes it.
 */
`;

const IMPORT_RE =
    /^[ \t]*import\s+(?:(\{[\s\S]*?\})|([A-Za-z0-9_$]+))\s+from\s+['"]([^'"]+)['"];?[ \t]*$/gm;
const BARE_IMPORT_RE = /^[ \t]*import\s+['"]([^'"]+)['"];?[ \t]*$/gm;
const EXPORT_RE = /^([ \t]*)export\s+(?=(?:async\s+)?(?:function|const|let|var|class)\b)/gm;
const DECL_RE =
    /^(?:export\s+)?(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z0-9_$]+)/gm;

/** Parse one module: its dependencies, its imported names, its exports. */
function analyse(source, filePath) {
    const deps = [];
    const imports = [];

    for (const match of source.matchAll(IMPORT_RE)) {
        const [, braced, defaultName, spec] = match;

        if (defaultName) {
            throw new Error(
                `${filePath}: default imports are not supported by this bundler.`,
            );
        }

        const names = braced
            .replace(/[{}]/g, '')
            .split(',')
            .map((n) => n.trim())
            .filter(Boolean)
            .map((n) => {
                if (n.includes(' as ')) {
                    throw new Error(
                        `${filePath}: "import as" is not supported by this bundler.`,
                    );
                }
                return n;
            });

        deps.push(spec);
        imports.push({ spec, names });
    }

    for (const match of source.matchAll(BARE_IMPORT_RE)) {
        deps.push(match[1]);
    }

    // "export { a as b }" would survive stripping and break the bundle.
    if (/^[ 	]*export\s*\{/m.test(source)) {
        throw new Error(`${filePath}: "export { ... }" lists are not supported by this bundler.`);
    }

    const declared = new Set();
    for (const match of source.matchAll(DECL_RE)) {
        declared.add(match[1]);
    }

    return { deps, imports, declared };
}

function strip(source) {
    return source
        .replace(IMPORT_RE, '')
        .replace(BARE_IMPORT_RE, '')
        .replace(EXPORT_RE, '$1');
}

const modules = new Map();

async function load(filePath) {
    if (modules.has(filePath)) return modules.get(filePath);

    let source;
    try {
        source = await readFile(filePath, 'utf8');
    } catch {
        throw new Error(`Cannot read module: ${filePath}`);
    }

    const info = analyse(source, relative(ROOT, filePath));
    const record = { filePath, source, ...info, resolved: [] };
    modules.set(filePath, record);

    for (const spec of info.deps) {
        const depPath = resolve(dirname(filePath), spec);
        record.resolved.push(depPath);
        await load(depPath);
    }

    return record;
}

/** Depth-first post-order: a module is emitted after everything it needs. */
function order(entryPath) {
    const out = [];
    const state = new Map();

    function visit(filePath, stack) {
        const seen = state.get(filePath);
        if (seen === 'done') return;
        if (seen === 'visiting') {
            const cycle = [...stack, filePath]
                .map((p) => relative(ROOT, p))
                .join(' -> ');
            throw new Error(`Import cycle: ${cycle}`);
        }

        state.set(filePath, 'visiting');
        const record = modules.get(filePath);

        for (const dep of record.resolved) {
            visit(dep, [...stack, filePath]);
        }

        state.set(filePath, 'done');
        out.push(record);
    }

    visit(entryPath, []);
    return out;
}

function validate(ordered) {
    const owners = new Map();
    const problems = [];

    for (const record of ordered) {
        const where = relative(ROOT, record.filePath);

        for (const name of record.declared) {
            if (owners.has(name)) {
                problems.push(
                    `Duplicate top-level name "${name}" in ${where} ` +
                        `(already declared in ${owners.get(name)}). ` +
                        `Concatenation flattens scope, so names must be unique.`,
                );
            } else {
                owners.set(name, where);
            }
        }
    }

    for (const record of ordered) {
        const where = relative(ROOT, record.filePath);

        for (const { spec, names } of record.imports) {
            const depPath = resolve(dirname(record.filePath), spec);
            const dep = modules.get(depPath);

            for (const name of names) {
                if (!dep.declared.has(name)) {
                    problems.push(
                        `${where} imports "${name}" from ${spec}, ` +
                            `which does not declare it.`,
                    );
                }
            }
        }
    }

    if (problems.length) {
        throw new Error('Build failed:\n  - ' + problems.join('\n  - '));
    }
}

async function main() {
    await load(ENTRY);

    const ordered = order(ENTRY);
    validate(ordered);

    const body = ordered
        .map((record) => {
            const where = relative(ROOT, record.filePath).replace(/\\/g, '/');
            return `/* ===== ${where} ===== */\n` + strip(record.source).trim();
        })
        .join('\n\n');

    const bundle =
        HEADER +
        '\n(function () {\n' +
        "    'use strict';\n\n" +
        `    const PI_BUILD_VERSION = '${VERSION}';\n` +
        // The code's own fingerprint: work kept between pages (the plan comparison) is never reused by other code,
        // even a rebuild with the same version.
        `    const PI_BUILD_HASH = '${createHash('sha256').update(body).digest('hex').slice(0, 12)}';\n\n` +
        indent(body) +
        '\n\n    boot();\n' +
        '})();\n';

    /*
     * Parse the bundle before writing it.
     *
     * v2.5.1 shipped a file that no browser could parse: a CSS comment inside
     * the styles template literal contained a backtick, which terminated the
     * string and broke the whole script. Tampermonkey silently ran nothing.
     * `node --check` caught it as a separate step and the failure was missed,
     * so the check belongs INSIDE the build where it cannot be skipped.
     */
    try {
        new vm.Script(bundle, { filename: 'torn-pumping-iron.user.js' });
    } catch (error) {
        throw new Error(
            'Bundle is not valid JavaScript and was NOT written: ' +
                error.message,
        );
    }

    await mkdir(dirname(OUT), { recursive: true });
    await writeFile(OUT, bundle, 'utf8');
    await writeFile(RELEASE_OUT, bundle, 'utf8');

    const kb = (Buffer.byteLength(bundle, 'utf8') / 1024).toFixed(1);
    console.log(
        `Built ${relative(ROOT, OUT)} from ${ordered.length} modules (${kb} KB).`,
    );
}

function indent(text) {
    return text
        .split('\n')
        .map((line) => (line.trim() ? '    ' + line : ''))
        .join('\n');
}

main().catch((error) => {
    console.error(error.message);
    process.exit(1);
});
