// ==UserScript==
// @name         Torn Pumping Iron
// @namespace    torn-pumping-iron
// @version      0.1.0
// @description  Gym planner and fight scout for Torn: what to take, what to train, what to buy, who you can beat. Reads the API and the page you're on; never acts for you.
// @author       abrahamdelosreyes17-oss
// @match        https://www.torn.com/*
// @match        https://abrahamdelosreyes17-oss.github.io/torn-pumping-iron/app.html*
// @run-at       document-idle
// @noframes
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_registerMenuCommand
// @grant        GM_openInTab
// @grant        GM_xmlhttpRequest
// @grant        GM_addValueChangeListener
// @grant        unsafeWindow
// @connect      api.torn.com
// @connect      weav3r.dev
// @connect      ffscouter.com
// @connect      www.tornstats.com
// @connect      workers.dev
// @downloadURL  https://raw.githubusercontent.com/abrahamdelosreyes17-oss/torn-pumping-iron/main/torn-pumping-iron.user.js
// @updateURL    https://raw.githubusercontent.com/abrahamdelosreyes17-oss/torn-pumping-iron/main/torn-pumping-iron.user.js
// ==/UserScript==

/*
 * Built from src/ by build.mjs - do not edit this file directly.
 *
 * Rules this script keeps, deliberately (see README.md):
 *   - Data comes from the Torn API or from the page you are viewing. It never
 *     requests a Torn page, and never uses a hidden tab or iframe.
 *   - It never acts for you: no train, buy, use or attack, and no clicks on
 *     Torn's buttons. "Fill" types one number into Torn's box on your click;
 *     you press TRAIN yourself.
 *   - No alerts, sounds or title changes from a Torn tab. Discord pings come
 *     only from your own Worker, which reads the API.
 *   - One Torn budget (70 a minute) shared by every tab, used only by a
 *     visible tab; each third party has its own client and budget.
 *   - Each key goes only to the service that issued it: the Torn key to
 *     api.torn.com, the FFScouter key to ffscouter.com, the TornStats key to
 *     tornstats.com. TornW3B gets item ids only.
 *   - The attack-page reader only copies Torn's response; it never changes it.
 */

(function () {
    'use strict';

    const PI_BUILD_VERSION = '0.1.0';

    /* ===== src/platform/gm.js ===== */
    /*
     * Userscript-host adapter.
     *
     * Every GM_* call in the project goes through this file. core/ and api/ never
     * touch it directly, so those layers stay portable to a plain web app: swap
     * this one module for a localStorage (or server) adapter and nothing else
     * changes.
     *
     * Falls back to an in-memory store when the GM_* globals are absent, which is
     * what lets the unit tests run under plain node.
     */

    const GM_NAMESPACE = 'pumpingIron.v1.';

    const gmMemoryStore = new Map();

    const gmHasStorage =
        typeof GM_getValue === 'function' && typeof GM_setValue === 'function';

    function gmKey(key) {
        return GM_NAMESPACE + key;
    }

    /** Read a JSON-serialisable value. Returns `fallback` if absent or corrupt. */
    function gmGet(key, fallback = null) {
        const full = gmKey(key);

        let raw;
        if (gmHasStorage) {
            raw = GM_getValue(full, null);
        } else {
            raw = gmMemoryStore.has(full) ? gmMemoryStore.get(full) : null;
        }

        if (raw === null || raw === undefined || raw === '') return fallback;

        try {
            return JSON.parse(raw);
        } catch {
            // A corrupt entry is not worth crashing over; treat it as absent.
            return fallback;
        }
    }

    /** Write a JSON-serialisable value. */
    function gmSet(key, value) {
        const full = gmKey(key);
        const raw = JSON.stringify(value);

        if (gmHasStorage) {
            GM_setValue(full, raw);
        } else {
            gmMemoryStore.set(full, raw);
        }
    }

    /** Remove a stored value. */
    function gmDel(key) {
        const full = gmKey(key);

        if (gmHasStorage && typeof GM_deleteValue === 'function') {
            GM_deleteValue(full);
        } else if (gmHasStorage) {
            GM_setValue(full, '');
        } else {
            gmMemoryStore.delete(full);
        }
    }

    /** Register a Tampermonkey menu command, if the host supports them. */
    function gmMenu(label, handler) {
        if (typeof GM_registerMenuCommand === 'function') {
            GM_registerMenuCommand(label, handler);
        }
    }

    /**
     * HTTP through the userscript host's own transport.
     *
     * A plain fetch() from a userscript runs in the PAGE's context and is subject
     * to Torn's Content-Security-Policy, which can block api.torn.com outright
     * (the trading app learned this the hard way: "it does not scan").
     * GM_xmlhttpRequest runs outside the page, so the CSP does not apply; every
     * host it reaches needs an `@connect` line in the header.
     *
     * Falls back to fetch when the host does not provide it (and under node, for
     * the tests).
     *
     * @param {string} url
     * @param {object} [init] - {method, headers, body}; GET when omitted
     * @returns {Promise<{ok: boolean, status: number, json: function, text: function}>}
     */
    function gmFetch(url, init = {}) {
        const method = (init && init.method) || 'GET';
        const headers = (init && init.headers) || {};
        const body = init && init.body !== undefined ? init.body : undefined;

        if (typeof GM_xmlhttpRequest !== 'function') {
            if (typeof fetch === 'function') {
                return method === 'GET' && !Object.keys(headers).length
                    ? fetch(url)
                    : fetch(url, { method, headers, body });
            }
            return Promise.reject(new Error('No HTTP transport available.'));
        }

        return new Promise((resolve, reject) => {
            GM_xmlhttpRequest({
                method,
                url,
                headers,
                data: body,
                timeout: 30000,
                onload(response) {
                    resolve({
                        ok: response.status >= 200 && response.status < 300,
                        status: response.status,
                        json: async () => JSON.parse(response.responseText),
                        text: async () => String(response.responseText || ''),
                    });
                },
                onerror() {
                    reject(new Error('Network request failed.'));
                },
                ontimeout() {
                    reject(new Error('Request timed out.'));
                },
            });
        });
    }

    /** Open a URL in a new tab, if the host supports it; otherwise fall back. */
    function gmOpenTab(url) {
        if (typeof GM_openInTab === 'function') {
            GM_openInTab(url, { active: true });
        } else if (typeof window !== 'undefined') {
            window.open(url, '_blank', 'noopener');
        }
    }

    /**
     * Be told when ANOTHER tab changes a stored value. This is how follower tabs
     * see the live feed the leader tab writes, without polling anything.
     * Returns false when the host has no listener API (the caller then re-reads
     * on its own timer).
     */
    function gmOnChange(key, handler) {
        if (typeof GM_addValueChangeListener !== 'function') return false;

        GM_addValueChangeListener(gmKey(key), (_name, _old, _new, remote) => {
            if (remote) handler();
        });

        return true;
    }

    /* ===== src/sources/route.js ===== */
    /*
     * Which page are we on? Pure string work, so it is testable.
     *
     * Every page the script marks is one the user opened; nothing here loads a
     * page. The harness stands in for Torn's pages with `?page=<name>` on its own
     * host (never on torn.com), the way the trading app's harness does.
     */

    const PAGE_GYM = 'gym';
    const PAGE_ITEMS = 'items';
    const PAGE_ITEM_MARKET = 'itemmarket';
    const PAGE_BAZAAR = 'bazaar';
    const PAGE_POINTS = 'points';
    const PAGE_PROFILE = 'profile';
    const PAGE_FACTION = 'faction';
    const PAGE_ATTACK = 'attack';
    const PAGE_OTHER = 'other';

    /** The webpage the script draws over (GitHub Pages, gh-pages branch). */
    const APP_PAGE_URL = 'https://abrahamdelosreyes17-oss.github.io/torn-pumping-iron/app.html';

    /** The harness boots the webpage on its own host with this marker. */
    const APP_PAGE_PARAM = 'pi';
    const APP_PAGE_VALUE = 'app';

    function queryOf(href) {
        try {
            return new URL(href).searchParams;
        } catch {
            return new URLSearchParams();
        }
    }

    function hostOf(href) {
        try {
            return new URL(href).hostname.toLowerCase();
        } catch {
            return '';
        }
    }

    function isTornHost(href) {
        return /(^|\.)torn\.com$/.test(hostOf(href));
    }

    /** A query value whatever its spelling (Torn's own links vary: XID, userId, userID). */
    function param(href, name) {
        const want = name.toLowerCase();
        for (const [k, v] of queryOf(href)) if (k.toLowerCase() === want) return v;
        // Some Torn pages keep their parameters in the hash (#/p=...&ID=5).
        const hash = String(href || '').split('#')[1] || '';
        for (const part of hash.replace(/^\/+/, '').split(/[&?]/)) {
            const [k, v] = part.split('=');
            if (k && k.toLowerCase() === want) return v || '';
        }
        return null;
    }

    function numParam(href, name) {
        const v = param(href, name);
        return v && /^\d+$/.test(v) ? v : null;
    }

    /**
     * @param {string} href - normally location.href
     * @returns {string} one of the PAGE_* constants
     */
    function detectPage(href) {
        if (typeof href !== 'string' || !href) return PAGE_OTHER;
        const url = href.toLowerCase();

        // The harness: ?page=gym etc. on a host that is not Torn.
        if (!isTornHost(href)) {
            const p = (queryOf(href).get('page') || '').toLowerCase();
            const known = [PAGE_GYM, PAGE_ITEMS, PAGE_ITEM_MARKET, PAGE_BAZAAR, PAGE_POINTS, PAGE_PROFILE, PAGE_FACTION, PAGE_ATTACK];
            return known.includes(p) ? p : PAGE_OTHER;
        }

        if (url.includes('/gym.php')) return PAGE_GYM;
        if (url.includes('/item.php')) return PAGE_ITEMS;
        if (url.includes('sid=itemmarket') || url.includes('/imarket.php')) return PAGE_ITEM_MARKET;
        if (url.includes('/bazaar.php')) return PAGE_BAZAAR;
        if (url.includes('/pmarket.php')) return PAGE_POINTS;
        if (url.includes('/profiles.php')) return PAGE_PROFILE;
        if (url.includes('/factions.php')) return PAGE_FACTION;
        if (url.includes('sid=attack') && url.includes('loader.php')) return PAGE_ATTACK;
        return PAGE_OTHER;
    }

    /** The player a profile page shows (profiles.php?XID=), or null. */
    function profileIdOf(href) {
        return detectPage(href) === PAGE_PROFILE ? numParam(href, 'XID') : null;
    }

    /** The defender on the attack page (loader.php?sid=attack&user2ID=), or null. */
    function attackTargetOf(href) {
        return detectPage(href) === PAGE_ATTACK ? numParam(href, 'user2ID') : null;
    }

    /** Whose bazaar this is (bazaar.php?userId=), or null for your own. */
    function bazaarOwnerId(href) {
        return detectPage(href) === PAGE_BAZAAR ? numParam(href, 'userId') : null;
    }

    /** The faction a faction page shows (factions.php?step=profile&ID=), or null (your own). */
    function factionIdOf(href) {
        return detectPage(href) === PAGE_FACTION ? numParam(href, 'ID') : null;
    }

    /** The item the Item Market page is showing (#/market/view=search&itemID=), or null. */
    function itemMarketItemOf(href) {
        return detectPage(href) === PAGE_ITEM_MARKET ? numParam(href, 'itemID') : null;
    }

    function isAppPageUrl(href) {
        if (String(href || '').split(/[?#]/)[0] === APP_PAGE_URL) return true;
        // The harness boots the webpage on its own page with the marker.
        return queryOf(href).get(APP_PAGE_PARAM) === APP_PAGE_VALUE && !isTornHost(href);
    }

    /* ---------------------------------------------------------- Torn links */

    /*
     * Every action in the app is a link to the exact Torn page (owner rule 6).
     * One click, one navigation: nothing is bought, used or trained.
     */

    const TORN = 'https://www.torn.com/';

    function gymUrl() {
        return TORN + 'gym.php';
    }

    function itemsUrl() {
        return TORN + 'item.php';
    }

    function pointsMarketUrl() {
        return TORN + 'pmarket.php';
    }

    function bazaarUrl(userId) {
        return TORN + 'bazaar.php?userId=' + encodeURIComponent(String(userId)) + '#/';
    }

    function itemMarketUrl(itemId) {
        return TORN + 'page.php?sid=ItemMarket#/market/view=search&itemID=' + encodeURIComponent(String(itemId));
    }

    function profileUrl(userId) {
        return TORN + 'profiles.php?XID=' + encodeURIComponent(String(userId));
    }

    function attackUrl(userId) {
        return TORN + 'loader.php?sid=attack&user2ID=' + encodeURIComponent(String(userId));
    }

    function factionUrl(factionId) {
        return TORN + 'factions.php?step=profile&ID=' + encodeURIComponent(String(factionId));
    }

    function apiKeyPageUrl() {
        return TORN + 'preferences.php#tab=api';
    }

    /* ===== src/main.js ===== */
    /*
     * Wiring. The only file that knows it is a userscript; core/ and api/ are
     * plain modules tested under node.
     *
     * Two entry points share it:
     *   - every Torn page: the overlay pill, the marks on the page being viewed,
     *     and Torn Eye chips;
     *   - the webpage (GitHub Pages app.html): the full tabs, drawn over the
     *     placeholder the page shows without the script.
     */




    function boot() {
        const href = typeof location !== 'undefined' ? location.href : '';
        const where = isAppPageUrl(href) ? 'app' : detectPage(href);
        gmSet('lastBoot', { at: Date.now(), where, version: PI_BUILD_VERSION });
        if (typeof document !== 'undefined' && document.documentElement) {
            document.documentElement.setAttribute('data-pi-booted', where);
        }
        return gmGet('lastBoot', null);
    }

    boot();
})();
